// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-practice-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/data.ts
var practice = {
  name: "Reigersbos Medical Center",
  address: "Reigersbos 100 K (3e etage), 1107 ES Amsterdam",
  phone: "020 737 14 26",
  fax: "020 737 03 79",
  email: "Info@reigersbosmedicalcenter.nl",
  openingHours: "Maandag t/m vrijdag 08:00\u201317:00. Zaterdag en zondag gesloten.",
  website: "https://reigersbosmedicalcenter.nl"
};
var emergency = {
  lifeThreatening: {
    number: "112",
    when: "Bij levensgevaar of een acute noodsituatie"
  },
  duringOpeningHours: {
    number: "020 737 14 26",
    when: "Maandag t/m vrijdag tot 17:00 \u2014 bel de praktijk en kies de spoedoptie"
  },
  outsideOpeningHours: {
    number: "088 003 06 00",
    when: "Avond, nacht en weekend",
    provider: "Huisartsenposten Amsterdam",
    website: "https://www.huisartsenpostenamsterdam.nl"
  }
};
var services = [
  {
    name: "Huisartsenzorg",
    description: "Reguliere huisartsenzorg: consulten, onderzoek, behandeling, verwijzingen en herhaalrecepten.",
    page: "/huisartspraktijk"
  },
  {
    name: "Praktijkassistente",
    description: "Eerste aanspreekpunt voor vragen, triage, uitslagen en kleine medische handelingen.",
    page: "/praktijkassistente"
  },
  {
    name: "POH-S (somatiek)",
    description: "Praktijkondersteuner voor chronische aandoeningen zoals diabetes, hart- en vaatziekten en COPD/asthma.",
    page: "/poh-s"
  },
  {
    name: "POH-GGZ",
    description: "Praktijkondersteuner geestelijke gezondheidszorg voor psychische klachten en begeleiding.",
    page: "/poh-ggz"
  },
  {
    name: "Fysiotherapie",
    description: "Fysiotherapie in hetzelfde gebouw, inclusief oefentherapie en revalidatie.",
    page: "/fysiotherapie"
  },
  {
    name: "Verloskunde",
    description: "Verloskundigenpraktijk De Poort, gevestigd in ons pand \u2014 begeleiding tijdens zwangerschap, bevalling en kraamperiode.",
    page: "/overig-zorgaanbod"
  },
  {
    name: "Bloedafname en diagnostiek",
    description: "RHMDC bloedafname en diagnostisch onderzoek op onze locatie.",
    page: "/overig-zorgaanbod"
  }
];
var team = [
  { name: "Julia van de Pol", role: "Huisarts", big: "59919561501" },
  { name: "Sandra Bediako", role: "Huisarts", big: "39918036001" },
  { name: "Warcha Ganpat", role: "Doktersassistent", big: null },
  { name: "Lois Oduro", role: "Doktersassistent", big: null },
  { name: "Derek Che", role: "Fysiotherapeut", big: "39915224904" },
  { name: "Sylvia Ohagwu", role: "Fysiotherapeut", big: "79928616104" }
];
var carePartners = [
  {
    name: "Verloskundigenpraktijk De Poort",
    category: "Verloskunde",
    description: "Kleinschalige verloskundigenpraktijk in ons pand. Persoonlijke begeleiding van de eerste maanden van de zwangerschap tot de eerste weken na de geboorte.",
    servicesOffered: [
      "Zwangerschapsbegeleiding",
      "Begeleiding bevalling",
      "Kraamzorg & nazorg",
      "Echo-onderzoek",
      "Prenatale screening",
      "Anticonceptiezorg"
    ],
    phone: "020 358 58 47",
    website: "https://www.verloskundigenpraktijkdepoort.nl",
    openingHours: null,
    note: "Aanmelden en afspraken maken gaat direct via De Poort, telefonisch of via hun website."
  },
  {
    name: "RHMDC Bloedafname",
    category: "Diagnostiek",
    description: "Het Reinier Haga Medisch Diagnostisch Centrum verzorgt diagnostisch onderzoek op onze locatie. U bent zonder afspraak welkom.",
    servicesOffered: [
      "Bloedonderzoek",
      "Fecesonderzoek",
      "Materiaal inleveren",
      "Soa onderzoek",
      "Urineonderzoek"
    ],
    phone: "088 260 4000",
    website: "https://www.rhmdc.nl/locaties/reigersbos-medical-center",
    openingHours: "Donderdag 09:00 \u2013 12:00 (overige dagen gesloten)",
    note: "Neem altijd uw aanvraagformulier (papier of digitaal) en legitimatiebewijs mee."
  }
];
var patientInfo = [
  {
    topic: "Inschrijven als pati\xEBnt",
    summary: "Nieuwe pati\xEBnten kunnen zich inschrijven via het inschrijfformulier op de website of telefonisch via de praktijk. Neem uw legitimatiebewijs en zorgverzekeringsgegevens mee.",
    page: "/"
  },
  {
    topic: "Herhaalrecept aanvragen",
    summary: "Herhaalmedicatie vraagt u aan via het herhaalrecept-formulier op de website of telefonisch. Aanvragen worden doorgaans binnen 2 werkdagen verwerkt en zijn daarna bij uw apotheek op te halen.",
    page: "/"
  },
  {
    topic: "Afspraak maken",
    summary: "Bel de praktijk op 020 737 14 26 tijdens openingstijden (ma\u2013vr 08:00\u201317:00). De assistente stelt enkele vragen om de juiste zorg en tijdsduur in te plannen.",
    page: "/contact"
  },
  {
    topic: "Klachten",
    summary: "Bent u niet tevreden? Bespreek dit eerst met uw huisarts of de praktijkmanager. Komt u er samen niet uit, dan kunt u de klachtenprocedure op de website volgen.",
    page: "/klachten"
  },
  {
    topic: "Omgangsregels",
    summary: "In de praktijk gelden omgangsregels voor een veilige en respectvolle omgeving. Spoedgevallen gaan voor, waarvoor wij uw begrip vragen.",
    page: "/omgangsregels"
  },
  {
    topic: "Privacy en medische gegevens",
    summary: "Wij verwerken uw gegevens volgens de AVG. Uitwisseling met de huisartsenpost, apotheek en specialisten gebeurt via Medicom, uitsluitend als dat voor uw zorg nodig is.",
    page: "/privacyreglement"
  },
  {
    topic: "Expats",
    summary: "Engelstalige informatie voor expats over inschrijven, het Nederlandse zorgsysteem, verzekering en het bezoeken van de huisarts.",
    page: "/expats"
  },
  {
    topic: "Ongedocumenteerde pati\xEBnten",
    summary: "Ook zonder verblijfsstatus of verzekering heeft u recht op medisch noodzakelijke zorg. Op de website staat hoe dit werkt en welke regelingen er zijn.",
    page: "/ongedocumenteerden"
  },
  {
    topic: "Vacatures",
    summary: "Openstaande vacatures binnen de praktijk, inclusief functie-eisen en de sollicitatieprocedure, staan op de vacaturepagina.",
    page: "/vacatures"
  }
];

// src/lib/mcp/tools/get-practice-info.ts
var get_practice_info_default = defineTool({
  name: "get_practice_info",
  title: "Praktijkinformatie",
  description: "Geeft de algemene praktijkgegevens van Reigersbos Medical Center: naam, adres, telefoon, fax, e-mail, openingstijden en website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          `${practice.name}`,
          `Adres: ${practice.address}`,
          `Telefoon: ${practice.phone}`,
          `Fax: ${practice.fax}`,
          `E-mail: ${practice.email}`,
          `Openingstijden: ${practice.openingHours}`,
          `Website: ${practice.website}`
        ].join("\n")
      }
    ],
    structuredContent: { practice }
  })
});

// src/lib/mcp/tools/get-emergency-contacts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_emergency_contacts_default = defineTool2({
  name: "get_emergency_contacts",
  title: "Spoednummers",
  description: "Geeft de spoednummers van Reigersbos Medical Center: 112 bij levensgevaar, de praktijk tijdens openingstijden en de huisartsenpost buiten openingstijden.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          `Levensgevaar: bel ${emergency.lifeThreatening.number} (${emergency.lifeThreatening.when})`,
          `Tijdens openingstijden: ${emergency.duringOpeningHours.number} (${emergency.duringOpeningHours.when})`,
          `Buiten openingstijden: ${emergency.outsideOpeningHours.number} \u2014 ${emergency.outsideOpeningHours.provider} (${emergency.outsideOpeningHours.when}), ${emergency.outsideOpeningHours.website}`
        ].join("\n")
      }
    ],
    structuredContent: { emergency }
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_services_default = defineTool3({
  name: "list_services",
  title: "Diensten",
  description: "Geeft een lijst van de zorgdiensten van Reigersbos Medical Center, met een korte omschrijving en de bijbehorende pagina op de website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: services.map((s) => `${s.name} \u2014 ${s.description} (${s.page})`).join("\n")
      }
    ],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-team-members.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var list_team_members_default = defineTool4({
  name: "list_team_members",
  title: "Team",
  description: "Geeft de zorgverleners van Reigersbos Medical Center met hun functie en, waar van toepassing, hun BIG-nummer. Optioneel te filteren op functie.",
  inputSchema: {
    role: z.string().optional().describe("Optioneel filter op functie, bijvoorbeeld 'Huisarts' of 'Fysiotherapeut'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const role = input?.role?.trim().toLowerCase();
    const members = role ? team.filter((m) => m.role.toLowerCase().includes(role)) : team;
    return {
      content: [
        {
          type: "text",
          text: members.length ? members.map((m) => `${m.name} \u2014 ${m.role}${m.big ? ` (BIG: ${m.big})` : ""}`).join("\n") : "Geen teamleden gevonden voor deze functie."
        }
      ],
      structuredContent: { members }
    };
  }
});

// src/lib/mcp/tools/list-care-partners.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_care_partners_default = defineTool5({
  name: "list_care_partners",
  title: "Zorgpartners",
  description: "Geeft de zorgpartners die in het pand van Reigersbos Medical Center werken (verloskunde en diagnostiek), met diensten, contactgegevens en openingstijden.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: carePartners.map(
          (p) => [
            `${p.name} (${p.category})`,
            p.description,
            `Diensten: ${p.servicesOffered.join(", ")}`,
            `Telefoon: ${p.phone}`,
            `Website: ${p.website}`,
            p.openingHours ? `Openingstijden: ${p.openingHours}` : null,
            p.note
          ].filter(Boolean).join("\n")
        ).join("\n\n")
      }
    ],
    structuredContent: { carePartners }
  })
});

// src/lib/mcp/tools/get-patient-info.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_patient_info_default = defineTool6({
  name: "get_patient_info",
  title: "Pati\xEBnteninformatie",
  description: "Zoekt in de publieke pati\xEBnteninformatie van Reigersbos Medical Center: inschrijven, herhaalrecept, afspraak maken, klachten, omgangsregels, privacy, expats, ongedocumenteerde pati\xEBnten en vacatures. Zonder zoekterm worden alle onderwerpen teruggegeven.",
  inputSchema: {
    query: z2.string().optional().describe("Optionele zoekterm, bijvoorbeeld 'herhaalrecept' of 'klacht'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const query = input?.query?.trim().toLowerCase();
    const topics = query ? patientInfo.filter(
      (t) => t.topic.toLowerCase().includes(query) || t.summary.toLowerCase().includes(query)
    ) : patientInfo;
    return {
      content: [
        {
          type: "text",
          text: topics.length ? topics.map((t) => `${t.topic}
${t.summary}
Pagina: ${t.page}`).join("\n\n") : "Geen informatie gevonden. Beschikbare onderwerpen: " + patientInfo.map((t) => t.topic).join(", ")
        }
      ],
      structuredContent: { topics }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "reigersbos-medical-center-mcp",
  title: "Reigersbos Medical Center",
  version: "0.1.0",
  instructions: "Publieke informatie over huisartsenpraktijk Reigersbos Medical Center in Amsterdam. Gebruik `get_practice_info` voor adres, telefoon en openingstijden, `get_emergency_contacts` voor spoed (112, praktijk, huisartsenpost), `list_services` voor het zorgaanbod, `list_team_members` voor zorgverleners, `list_care_partners` voor verloskunde en bloedafname in het pand, en `get_patient_info` voor onderwerpen zoals inschrijven, herhaalrecept, klachten en privacy. Deze server geeft alleen algemene, publieke informatie en nooit medisch advies of pati\xEBntgegevens.",
  tools: [
    get_practice_info_default,
    get_emergency_contacts_default,
    list_services_default,
    list_team_members_default,
    list_care_partners_default,
    get_patient_info_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
